site_name: E3TTS

markdown_extensions:
  - pymdownx.arithmatex

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

nav:
  - E3tts: about.md
  - UNet: unet.md

theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
  palette:
    scheme: slate  # Enables the dark theme